"use client";

import { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Calendar, CalendarDays, Clock, AlertTriangle, CheckCircle, FileText, DollarSign, RefreshCw } from "lucide-react";
import { useComplianceEvents } from '@/hooks/use-compliance-events';
import type { ComplianceEvent } from '@/types/compliance-events';

interface ComplianceCalendarProps {
  showAutoGenerated?: boolean;
  jurisdictionFilter?: number;
  className?: string;
}

export function ComplianceCalendar({ 
  showAutoGenerated = true, 
  jurisdictionFilter,
  className 
}: ComplianceCalendarProps) {
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth());
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  
  // Build filters for compliance events
  const filters = useMemo(() => {
    const fromDate = new Date(selectedYear, selectedMonth, 1);
    const toDate = new Date(selectedYear, selectedMonth + 1, 0);
    
    return {
      due_date_after: fromDate.toISOString().split('T')[0],
      due_date_before: toDate.toISOString().split('T')[0],
      jurisdiction_id: jurisdictionFilter,
    };
  }, [selectedMonth, selectedYear, jurisdictionFilter]);

  const { events, loading, error, refetch } = useComplianceEvents(filters);

  // Filter events based on auto-generated preference
  const filteredEvents = useMemo(() => {
    if (!showAutoGenerated) {
      return events.filter(event => !event.event_data?.auto_generated);
    }
    return events;
  }, [events, showAutoGenerated]);

  // Group events by date
  const eventsByDate = useMemo(() => {
    const grouped: Record<string, ComplianceEvent[]> = {};
    
    filteredEvents.forEach(event => {
      const dateKey = event.due_date.split('T')[0];
      if (!grouped[dateKey]) {
        grouped[dateKey] = [];
      }
      grouped[dateKey].push(event);
    });
    
    return grouped;
  }, [filteredEvents]);

  // Generate calendar days for the selected month
  const calendarDays = useMemo(() => {
    const daysInMonth = new Date(selectedYear, selectedMonth + 1, 0).getDate();
    const firstDay = new Date(selectedYear, selectedMonth, 1).getDay();
    
    const days = [];
    
    // Add empty cells for days before the first day of the month
    for (let i = 0; i < firstDay; i++) {
      days.push(null);
    }
    
    // Add days of the month
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${selectedYear}-${String(selectedMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      days.push({
        day,
        dateStr,
        events: eventsByDate[dateStr] || []
      });
    }
    
    return days;
  }, [selectedYear, selectedMonth, eventsByDate]);

  const getEventIcon = (event: ComplianceEvent) => {
    switch (event.event_type) {
      case 'filing':
        return <FileText className="h-3 w-3" />;
      case 'payment':
        return <DollarSign className="h-3 w-3" />;
      case 'wage_base_reset':
        return <RefreshCw className="h-3 w-3" />;
      default:
        return <CalendarDays className="h-3 w-3" />;
    }
  };

  const getEventPriorityColor = (priority: string, isAutoGenerated: boolean) => {
    const baseColor = priority === 'critical' ? 'destructive' : 
                     priority === 'high' ? 'orange' : 
                     priority === 'medium' ? 'yellow' : 'secondary';
    
    return isAutoGenerated ? `${baseColor} opacity-75` : baseColor;
  };

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  if (loading) {
    return (
      <Card className={className}>
        <CardContent className="p-6">
          <div className="flex items-center justify-center">
            <Clock className="h-5 w-5 animate-spin mr-2" />
            Loading compliance calendar...
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className={className}>
        <CardContent className="p-6">
          <div className="flex items-center text-destructive">
            <AlertTriangle className="h-5 w-5 mr-2" />
            Error loading compliance events: {error}
            <Button onClick={refetch} variant="outline" size="sm" className="ml-4">
              Retry
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className={className}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center">
            <Calendar className="h-5 w-5 mr-2" />
            Compliance Calendar
            {showAutoGenerated && (
              <Badge variant="outline" className="ml-2">
                Including Auto-Generated
              </Badge>
            )}
          </CardTitle>
          <div className="flex items-center space-x-2">
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(parseInt(e.target.value))}
              className="px-3 py-1 border rounded-md text-sm"
            >
              {monthNames.map((name, index) => (
                <option key={index} value={index}>{name}</option>
              ))}
            </select>
            <select
              value={selectedYear}
              onChange={(e) => setSelectedYear(parseInt(e.target.value))}
              className="px-3 py-1 border rounded-md text-sm"
            >
              {[selectedYear - 1, selectedYear, selectedYear + 1].map(year => (
                <option key={year} value={year}>{year}</option>
              ))}
            </select>
            <Button onClick={refetch} variant="outline" size="sm">
              <RefreshCw className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {/* Calendar Header */}
        <div className="grid grid-cols-7 gap-2 mb-4">
          {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
            <div key={day} className="p-2 text-center text-sm font-medium text-muted-foreground">
              {day}
            </div>
          ))}
        </div>

        {/* Calendar Grid */}
        <div className="grid grid-cols-7 gap-2">
          {calendarDays.map((dayData, index) => (
            <div
              key={index}
              className={`
                min-h-[100px] p-2 border rounded-lg
                ${dayData ? 'bg-background' : ''}
                ${dayData?.events.length ? 'border-primary/20' : 'border-border'}
              `}
            >
              {dayData && (
                <>
                  <div className="text-sm font-medium mb-2">{dayData.day}</div>
                  <div className="space-y-1">
                    {dayData.events.slice(0, 3).map(event => {
                      const isAutoGenerated = event.event_data?.auto_generated;
                      return (
                        <div
                          key={event.id}
                          className={`
                            text-xs p-1 rounded border-l-2 cursor-pointer
                            ${event.priority === 'critical' ? 'border-l-red-500 bg-red-50' :
                              event.priority === 'high' ? 'border-l-orange-500 bg-orange-50' :
                              event.priority === 'medium' ? 'border-l-yellow-500 bg-yellow-50' :
                              'border-l-blue-500 bg-blue-50'}
                            ${isAutoGenerated ? 'opacity-75 italic' : ''}
                          `}
                          title={`${event.title}\n${event.description || ''}\n${isAutoGenerated ? '(Auto-generated from tax config)' : ''}`}
                        >
                          <div className="flex items-center">
                            {getEventIcon(event)}
                            <span className="ml-1 truncate">{event.title}</span>
                          </div>
                          {isAutoGenerated && (
                            <div className="text-xs text-muted-foreground mt-1">
                              Auto-generated
                            </div>
                          )}
                        </div>
                      );
                    })}
                    {dayData.events.length > 3 && (
                      <div className="text-xs text-muted-foreground p-1">
                        +{dayData.events.length - 3} more...
                      </div>
                    )}
                  </div>
                </>
              )}
            </div>
          ))}
        </div>

        {/* Legend */}
        <div className="mt-6 pt-4 border-t">
          <div className="text-sm font-medium mb-2">Legend</div>
          <div className="flex flex-wrap gap-4 text-xs">
            <div className="flex items-center">
              <FileText className="h-3 w-3 mr-1" />
              Filing
            </div>
            <div className="flex items-center">
              <DollarSign className="h-3 w-3 mr-1" />
              Payment
            </div>
            <div className="flex items-center">
              <RefreshCw className="h-3 w-3 mr-1" />
              Wage Base Reset
            </div>
            <div className="flex items-center">
              <div className="w-3 h-3 bg-red-500 rounded mr-1"></div>
              Critical
            </div>
            <div className="flex items-center">
              <div className="w-3 h-3 bg-orange-500 rounded mr-1"></div>
              High
            </div>
            <div className="flex items-center">
              <div className="w-3 h-3 bg-yellow-500 rounded mr-1"></div>
              Medium
            </div>
            {showAutoGenerated && (
              <div className="flex items-center">
                <div className="w-3 h-3 bg-blue-500 opacity-75 rounded mr-1"></div>
                Auto-generated
              </div>
            )}
          </div>
        </div>

        {/* Summary */}
        <div className="mt-4 p-4 bg-muted/50 rounded-lg">
          <div className="text-sm">
            <div className="font-medium mb-2">This Month's Summary</div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-xs">
              <div>
                <div className="font-medium">Total Events</div>
                <div>{filteredEvents.length}</div>
              </div>
              <div>
                <div className="font-medium">Auto-Generated</div>
                <div>{filteredEvents.filter(e => e.event_data?.auto_generated).length}</div>
              </div>
              <div>
                <div className="font-medium">High Priority</div>
                <div>{filteredEvents.filter(e => e.priority === 'high' || e.priority === 'critical').length}</div>
              </div>
              <div>
                <div className="font-medium">Upcoming (Next 7 days)</div>
                <div>{filteredEvents.filter(e => {
                  const eventDate = new Date(e.due_date);
                  const weekFromNow = new Date();
                  weekFromNow.setDate(weekFromNow.getDate() + 7);
                  return eventDate <= weekFromNow && eventDate >= new Date();
                }).length}</div>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}